<!-- Author(s)  : E. Poldervaart                         -->
<!-- Created    : 23-08-2006                             -->
<!-- Name       : VDL Jonckheere Object Browser             -->
<!-- Copyright  : HawarIT BV                             -->
<!--            : De Wymerts 7                           -->
<!--            : 8701 WT Bolsward                       -->
<!--            :                                        -->
<!--            : Tel   : +31 (0)515 570333              -->
<!--            : Fax   : +31 (0)515 570335              -->
<!--            : WWW   : www.hawarIT.com                -->
<!--            : E-Mail: info@hawarIT.com               -->